# Generated by Django 5.0.3 on 2024-03-09 09:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=100)),
                ('phone_number', models.CharField(max_length=15)),
                ('dni', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('address', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Pet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('animal_type', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('weight', models.CharField(max_length=100)),
                ('illness', models.CharField(max_length=100)),
                ('breed', models.CharField(default='Unknown', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shelter.user')),
                ('economic_status', models.CharField(max_length=100)),
                ('housing_type', models.CharField(max_length=100)),
            ],
            bases=('shelter.user',),
        ),
        migrations.CreateModel(
            name='Worker',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='shelter.user')),
                ('salary', models.IntegerField()),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
            bases=('shelter.user',),
        ),
        migrations.CreateModel(
            name='Adopt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('pet', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.pet')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.customer')),
                ('worker', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shelter.worker')),
            ],
        ),
    ]
