# Generated by Django 5.0.3 on 2024-03-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('In recovery', 'In recovery')], default='Dog', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='illness',
            field=models.CharField(choices=[('Healthy', 'Healthy'), ('Sick', 'Sick'), ('In recovery', 'In recovery')], default='Healthy', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='weight',
            field=models.IntegerField(),
        ),
    ]
