# Generated by Django 5.0.3 on 2024-03-09 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_user_pet_remove_post_owner_remove_profile_user_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='age',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='worker',
            name='salary',
            field=models.IntegerField(),
        ),
    ]
