# Generated by Django 5.0.3 on 2024-03-27 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shelter', '0002_alter_pet_animal_type_alter_pet_illness_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='pet',
            name='is_adopted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='pet',
            name='animal_type',
            field=models.CharField(choices=[('dog', 'Dog'), ('cat', 'Cat'), ('bird', 'Bird'), ('fish', 'Fish'), ('reptile', 'Reptile'), ('rodent', 'Rodent'), ('other', 'Other')], default='Dog', max_length=100),
        ),
        migrations.AlterField(
            model_name='pet',
            name='illness',
            field=models.CharField(choices=[('healthy', 'Healthy'), ('sick', 'Sick'), ('in_recovery', 'In recovery')], default='Healthy', max_length=100),
        ),
    ]
